### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by pavelperc** [QwertygidQ/isd_homework_1#2]
Я не очень силён в питоне.. Зачем эти точки в пакете? Оно не хочет запускаться. Запуск по readme даёт пустую строку.
![image](https://user-images.githubusercontent.com/31820550/69486416-9f437600-0e5c-11ea-9bbb-6c28dcb40c13.png)
Если их убрать, то падает в другом месте:
    from ..config import Config
ValueError: attempted relative import beyond top-level package

**Comment by pavelperc** [comment]
Почему по умолчанию сервер 0.0.0.0, а не localhost?

**Comment by taiypeo** [comment]
Должно быть так:
```
(venv) [qwertygid@qwertygid-pc Python]$ ls
adam  ChessBot  hse  isd_homework_1  Notebooks  venn.zip  VTBackend
(venv) [qwertygid@qwertygid-pc Python]$ python3 -m isd_homework_1
 * Serving Flask app "isd_homework_1.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
```

Через PyCharm запустить просто файл не получится, поскольку подразумевается запуск package.

Pull request я все равно принял.

**Comment by pavelperc** [comment]
Видимо только на linux запускается. Я из внешней папки пробовал запускать. Не хотело.
